version: '3.8'
networks:
 traefik-public:
   external: true
 traefik:
   external: true
services:
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - assistant_config:/config
      - /etc/localtime:/etc/localtime:ro
    networks:
      - traefik
    environment:
      - TZ=America/Santiago
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.udp.routers.homeassistant.entrypoints=dnscrypt-udp"
        - "traefik.udp.routers.homeassistant.service=homeassistant@docker"
        - "traefik.udp.services.homeassistant.loadbalancer.server.port=5353/udp"
        - "traefik.http.routers.homeassistant.rule=Host(`homeassistant.local.${DOMAIN_NAME}`)"
        - "traefik.http.routers.homeassistant.service=homeassistant@docker"
        - "traefik.http.routers.homeassistant-http.entrypoints=web"
        - "traefik.http.routers.homeassistant-http.rule=Host(`homeassistant.local.${DOMAIN_NAME}`)"
        - "traefik.http.routers.homeassistant.entrypoints=websecure"
        - "traefik.http.routers.homeassistant-http.middlewares=homeassistant-https@docker"
        - "traefik.http.middlewares.homeassistant-https.redirectscheme.scheme=https"
        - "traefik.http.routers.homeassistant.tls=true"
        - "traefik.http.routers.homeassistant.tls.certresolver=le"
        - "traefik.http.services.homeassistant.loadbalancer.server.port=8080"
        - "traefik.docker.network=traefik-public"
volumes:
  assistant_config: {}