version: '3.8'

services:
  security-redis:
    image: bitnami/redis:latest
    secrets:
      - redis_password
    volumes:
      - redis-data:/data
    networks:
      - traefik-public
      - security-internal
    environment:
      - REDIS_PASSWORD_FILE=/run/secrets/redis_password
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        # TCP routing for Redis
        - "traefik.tcp.routers.security-redis.rule=HostSNI(`security-redis.${LOCAL_DOMAIN?err}`)"
        - "traefik.tcp.routers.security-redis.entrypoints=host-internal"
        - "traefik.tcp.routers.security-redis.tls=true"
        - "traefik.tcp.routers.security-redis.tls.certresolver=le-dns"
        - "traefik.tcp.services.security-redis.loadbalancer.server.port=6379"
        - "traefik.swarm.network=traefik-public"

  ntopng-proxy:
    image: caddy:2
    networks:
      - traefik-public
    configs:
      - source: ntopng_caddyfile
        target: /etc/caddy/Caddyfile
    environment:
      - NTOPNG_UPSTREAM=${HOST_DOCKER_GW?err}:3005
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.ntopng.rule=Host(`ntopng.${LOCAL_DOMAIN?err}`)"
        - "traefik.http.routers.ntopng.entrypoints=websecure"
        - "traefik.http.routers.ntopng.tls=true"
        - "traefik.http.routers.ntopng.tls.certresolver=le-dns"
        - "traefik.http.routers.ntopng.middlewares=authelia@swarm"
        - "traefik.http.services.ntopng.loadbalancer.server.port=3006"
        - "traefik.swarm.network=traefik-public"

secrets:
  redis_password:
    file: ../../secrets/redis/redis_password

volumes:
  redis-data:
    driver: local

networks:
  security-internal:
    driver: overlay
    attachable: false
  traefik-public:
    external: true

configs:
  ntopng_caddyfile:
    name: ntopng_caddyfile-${CONFIG_VERSION:-0}
    file: ./configs/ntopng/Caddyfile
