listening-port={{ env "BROWSER_LAB_TURN_PORT" }}
min-port=49160
max-port=49179
external-ip={{ env "BROWSER_LAB_TURN_EXTERNAL_IP" }}
fingerprint
lt-cred-mech
realm={{ env "BROWSER_LAB_TURN_REALM" }}
user={{ env "BROWSER_LAB_TURN_USER" }}:{{ secret "turn-password" }}
no-cli
no-tls
no-dtls
