model_list:
  # OpenAI Models with correct format
  - model_name: gpt-4o-mini
    litellm_params:
      model: openai/gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY
    model_info:
      owned_by: openai

  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o
      api_key: os.environ/OPENAI_API_KEY
    model_info:
      owned_by: openai
      
  # Ollama Models
  - model_name: gemma3-1b
    litellm_params:
      model: ollama/gemma3:1b
      api_base: http://ollama:11434
    model_info:
      owned_by: google
      
  - model_name: llama3-1b
    litellm_params:
      model: ollama/llama3.2:1b
      api_base: http://ollama:11434
    model_info:
      owned_by: meta
      
  - model_name: phi4-mini
    litellm_params:
      model: ollama/phi4-mini
      api_base: http://ollama:11434
    model_info:
      owned_by: microsoft
      
  - model_name: mistral
    litellm_params:
      model: ollama/mistral
      api_base: http://ollama:11434
    model_info:
      owned_by: mistral
      
  - model_name: moondream
    litellm_params:
      model: ollama/moondream
      api_base: http://ollama:11434
    model_info:
      owned_by: vikhyatk
      
  - model_name: neural-chat
    litellm_params:
      model: ollama/neural-chat
      api_base: http://ollama:11434
    model_info:
      owned_by: intel
      
  - model_name: starling-lm
    litellm_params:
      model: ollama/starling-lm
      api_base: http://ollama:11434
    model_info:
      owned_by: berkeley-nest
      
  - model_name: llama2-uncensored
    litellm_params:
      model: ollama/llama2-uncensored
      api_base: http://ollama:11434
    model_info:
      owned_by: meta
      
  - model_name: llava
    litellm_params:
      model: ollama/llava
      api_base: http://ollama:11434
    model_info:
      owned_by: lmsys
      
  - model_name: codellama
    litellm_params:
      model: ollama/codellama
      api_base: http://ollama:11434
    model_info:
      owned_by: meta
      
  - model_name: deepseek-r1
    litellm_params:
      model: ollama/deepseek-r1
      api_base: http://ollama:11434
    model_info:
      owned_by: deepseek
      
  - model_name: granite3-2
    litellm_params:
      model: ollama/granite3.2
      api_base: http://ollama:11434
    model_info:
      owned_by: google
      
  - model_name: llama3-1
    litellm_params:
      model: ollama/llama3.1
      api_base: http://ollama:11434
    model_info:
      owned_by: meta
      
  - model_name: nomic-embed-text
    litellm_params:
      model: ollama/nomic-embed-text
      api_base: http://ollama:11434
    model_info:
      owned_by: nomic
