
# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret docker_CDIR_block
recorder:
  db_url: !secret database_connection_url

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
