{
 "title": "Traefik Service Dashboard",
 "description": "Traefik dashboard prometheus",
 "tags": [
  "traefik",
  "prometheus",
  "networking",
  "reverse-proxy",
  "services"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(traefik_service_requests_total, service)"
   },
   {
    "name": "entrypoint",
    "label": "Entrypoint",
    "query": "label_values(traefik_entrypoint_requests_total, entrypoint)"
   },
   { "name": "code", "query": "label_values(code)" }
  ]
 },
 "panels": [
  { "title": "Service Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Traefik Services",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count by(service) (traefik_service_requests_total))"
    }
   ]
  },
  {
   "title": "Service Response Time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_request_duration_seconds_sum{service=~\"$service\"}[5m])) / sum(rate(traefik_service_request_duration_seconds_count{service=~\"$service\"}[5m]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Service Response Time Distribution",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(traefik_service_request_duration_seconds_sum[5m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Total Requests by Service (last 5min)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{service=~\"$service\"}[5m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "Entrypoints & Global Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Status code 200 over 5min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{entrypoint=~\"$entrypoint\",code=\"200\"}[5m])) by (method, code)",
     "legendFormat": "{{method}} : {{code}}"
    }
   ]
  },
  {
   "title": "Service Error Codes (last 5min)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{service=~\"$service\",code!=\"200\"}[5m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Requests by service",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total[5m])) by (service) ",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Requests by Entrypoint",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{entrypoint =~ \"$entrypoint\"}[5m])) by (entrypoint) ",
     "legendFormat": "{{ entrypoint }}"
    }
   ]
  }
 ]
}