version: "3.8"
networks:
  local:
  traefik-public:
    external: true
  traefik:
    external: true
services:
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    configs:
      - source: assistant_config_file
        target: /config/configuration.yaml
      - source: assistant_secrets_file
        target: /config/secrets.yaml
    volumes:
      # - assistant_config:/config
      - /etc/localtime:/etc/localtime:ro
    networks:
      - traefik
      - local
    environment:
      - TZ=America/Santiago
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"
        # UDP traffic
        - "traefik.udp.routers.homeassistant.entrypoints=discovery-udp"
        - "traefik.udp.routers.homeassistant.service=homeassistant@docker"
        - "traefik.udp.services.homeassistant.loadbalancer.server.port=5353/udp"
        - "traefik.http.routers.homeassistant.rule=Host(`homeassistant.${LOCAL_DOMAIN}`)"
        - "traefik.http.routers.homeassistant.service=homeassistant@docker"
        - "traefik.http.routers.homeassistant-http.entrypoints=web"
        - "traefik.http.routers.homeassistant-http.rule=Host(`homeassistant.${LOCAL_DOMAIN}`)"
        - "traefik.http.routers.homeassistant.entrypoints=websecure"
        - "traefik.http.routers.homeassistant-http.middlewares=homeassistant-https@docker"
        - "traefik.http.middlewares.homeassistant-https.redirectscheme.scheme=https"
        - "traefik.http.routers.homeassistant.tls=true"
        - "traefik.http.routers.homeassistant.tls.certresolver=le-dns"
        - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"
  mosquitto:
    image: eclipse-mosquitto
    configs:
      - source: mosquitto_config
        target: /mosquitto/config/mosquitto.conf
    networks:
      - local
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - /var/hacluster/mosquitto:/mosquitto
    deploy:
      replicas: 1
volumes:
  assistant_config: {}
configs:
  assistant_secrets_file:
    name: assistant_secrets.yaml-${CONFIG_VERSION:-0}
    file: ../configs/homeassistant/secrets.yaml
  assistant_config_file:
    name: configuration.yaml-${CONFIG_VERSION:-0}
    file: ../configs/homeassistant/configuration.yaml
  mosquitto_config:
    name: mosquitto.conf-${CONFIG_VERSION:-0}
    file: ../configs/mosquitto/mosquitto.conf
