services:
  mcp-grafana:
    image: mcp/grafana:latest
    environment:
      - GRAFANA_URL=http://grafana:3000
      - GRAFANA_API_KEY=${MCP_ADMIN_GRAFANA_API_KEY:?err}
    networks:
      - traefik
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        # Basic routing
        - traefik.http.routers.mcp-grafana-http.entrypoints=web
        - traefik.http.routers.mcp-grafana-http.rule=Host(`mcp-grafana.${LOCAL_DOMAIN}`)
        - traefik.http.routers.mcp-grafana.entrypoints=websecure
        - traefik.http.routers.mcp-grafana.rule=Host(`mcp-grafana.${LOCAL_DOMAIN}`)
        - traefik.http.routers.mcp-grafana.tls=true
        - traefik.http.routers.mcp-grafana.tls.certresolver=le-dns
        
        # Service configuration with extended timeout parameters
        - traefik.http.services.mcp-grafana.loadbalancer.server.port=8000
        - traefik.http.services.mcp-grafana.loadbalancer.passHostHeader=true
        - traefik.http.services.mcp-grafana.loadbalancer.responseForwarding.flushInterval=100ms
        
        # Simple redirect middleware
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        
        # Enhanced SSE-specific headers middleware
        - traefik.http.middlewares.sse-headers.headers.customResponseHeaders.Cache-Control=no-cache
        - traefik.http.middlewares.sse-headers.headers.customResponseHeaders.Connection=keep-alive
        - traefik.http.middlewares.sse-headers.headers.customResponseHeaders.X-Accel-Buffering=no
        - traefik.http.middlewares.sse-headers.headers.customResponseHeaders.Pragma=no-cache
        
        # Apply middlewares to router
        - traefik.http.routers.mcp-grafana-http.middlewares=https-redirect
        - traefik.http.routers.mcp-grafana.middlewares=sse-headers
networks:
  traefik:
    external: true