version: "3.9"
networks:
  traefik-public:
    external: true
  traefik:
    external: true
  prometheus:
    external: true
services:
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    hostname: "{{.Node.Hostname}}"
    environment:
      - NODE_ID={{.Node.ID}}
    networks:
      - traefik
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.sysfs=/host/sys"
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)"
      - "--no-collector.ipvs"
    deploy:
      mode: global
      resources:
        limits:
          cpus: "0.8"
          memory: 512M
        reservations:
          cpus: "0.2"
          memory: 64M
      placement:
        constraints:
          - node.platform.os == linux
      labels:
        - "traefik.enable=false"
        - "traefik.swarm.network=traefik"
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    hostname: "{{.Node.Hostname}}"
    networks:
      - traefik
    command:
      - "--logtostderr"
      - "--docker_only=true"
      - "--housekeeping_interval=15s"
      - "--store_container_labels=true"
      - "--storage_driver_password=${REDIS_PASSWORD?err}"
      - "--storage_driver=redis"
      - "--storage_driver_host=${REDIS_HOST:?err}:${REDIS_PORT:?err}"
    volumes:
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /sys:/sys:ro
      - /var/run:/var/run:ro
      - /:/rootfs:ro
      - /sys/fs/cgroup:/cgroup:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /etc/localtime:/etc/localtime:ro
    deploy:
      mode: global
      update_config:
        order: start-first
      placement:
        constraints:
         - node.platform.os == linux
         - node.platform.arch != aarch64
      labels:
        - "traefik.enable=true"
        - "traefik.swarm.network=traefik"
        - "traefik.http.routers.cadvisor.service=cadvisor@swarm"
        - "traefik.http.routers.cadvisor.rule=Host(`cadvisor.${LOCAL_DOMAIN:-traefik.me}`)"
        - "traefik.http.routers.cadvisor.entrypoints=websecure"
        - "traefik.http.routers.cadvisor.tls=true"
        - "traefik.http.routers.cadvisor.tls.certresolver=le-dns"
        - "traefik.http.services.cadvisor.loadbalancer.server.port=8080"
      resources:
        limits:
          memory: 512M
        reservations:
          cpus: "0.05"
          memory: 128M
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: wget --quiet --tries=1 --spider http://localhost:8080/healthz || exit 1
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 30s
  renderer:
    image: grafana/grafana-image-renderer:latest
    networks:
      - traefik
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
  nextdns-exporter:
    image: ghcr.io/raylas/nextdns-exporter:0.6.0
    networks:
      - traefik
    environment:
      - NEXTDNS_PROFILE=${NEXTDNS_PROFILE?err}
      - NEXTDNS_API_KEY=${NEXTDNS_API_KEY?err}
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 128M
        reservations:
          memory: 32M
      labels:
        - "traefik.enable=false"
        - "traefik.swarm.network=traefik"
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 60s
  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    networks:
      - traefik
      - prometheus
    configs:
      - source: blackbox_config
        target: /etc/blackbox_exporter/blackbox.yml
    command:
      - --config.file=/etc/blackbox_exporter/blackbox.yml
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 60s
      labels:
        - "traefik.enable=false"
        - "traefik.swarm.network=traefik"
  docker-health-telegraf:
    image: telegraf:1.37.3
    user: "0:0"
    entrypoint:
      - telegraf
    command:
      - --config
      - /etc/telegraf/telegraf.conf
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    configs:
      - source: telegraf_docker_health_config
        target: /etc/telegraf/telegraf.conf
    deploy:
      mode: global
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 60s
      placement:
        constraints:
          - node.platform.os == linux
      labels:
        - "traefik.enable=false"
        - "traefik.swarm.network=traefik"
  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:v0.18.0
    networks:
      - traefik
    configs:
      - source: postgres_exporter_queries
        target: /etc/postgres_exporter/queries.yaml
    secrets:
      - source: postgres_exporter_db_password
        target: /run/secrets/postgres_exporter_db_password
    environment:
      - DATA_SOURCE_URI=main-storage_postgres:5432/k8s_collective?sslmode=disable
      - DATA_SOURCE_USER=locutus
      - DATA_SOURCE_PASS_FILE=/run/secrets/postgres_exporter_db_password
    command:
      - --collector.stat_statements
      - --collector.stat_bgwriter
      - --collector.database_wraparound
      - --collector.long_running_transactions
      - --collector.process_idle
      - --collector.postmaster
      - --collector.stat_activity_autovacuum
      - --collector.stat_checkpointer
      - --collector.stat_database
      - --collector.stat_user_tables
      - --collector.statio_user_tables
      - --collector.replication_slot
      - --collector.locks
      - --web.listen-address=:9187
      - --extend.query-path=/etc/postgres_exporter/queries.yaml
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 60s
      placement:
        constraints:
          - node.labels.storage.manager == true
          - node.labels.load.tier == heavy
          - node.labels.node.ephemeral != true
      labels:
        - "traefik.enable=false"
        - "traefik.swarm.network=traefik"
  # netdata:
  #   image: netdata/netdata:edge
  #   pid: host
  #   hostname: "{{.Node.ID}}"
  #   networks:
  #     - traefik
  #   cap_add:
  #     - SYS_PTRACE
  #     - SYS_ADMIN
  #   security_opt:
  #     - apparmor:unconfined
  #   environment:
  #     - NETDATA_CLAIM_TOKEN=${NETDATA_TOKEN?err}
  #     - NETDATA_CLAIM_URL=https://app.netdata.cloud
  #     - NETDATA_CLAIM_ROOMS=${NETDATA_CLAIM_ROOMS?err}
  #   volumes:
  #     - netdataconfig:/etc/netdata
  #     - netdatalib:/var/lib/netdata
  #     - netdatacache:/var/cache/netdata
  #     - /etc/passwd:/host/etc/passwd:ro
  #     - /etc/group:/host/etc/group:ro
  #     - /etc/localtime:/etc/localtime:ro
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
  #     - /etc/os-release:/host/etc/os-release:ro
  #     - /etc/hostname:/etc/hostname:ro
  #     - /var/log:/host/var/log:ro
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   deploy:
  #     mode: global
  #     restart_policy:
  #       condition: on-failure
  #       delay: 5s
  #       max_attempts: 3
  #       window: 120s
  #     placement:
  #       constraints: [node.platform.os == linux]
  #     resources:
  #       limits:
  #         memory: 512M
  #       reservations:
  #         memory: 128M
  #     labels:
  #       - "traefik.enable=true"
  #       - "traefik.http.routers.netdata.rule=Host(`netdata.${LOCAL_DOMAIN:-home}`)"
  #       - "traefik.http.routers.netdata.entrypoints=web"
  #       - "traefik.http.routers.netdata.service=netdata@swarm"
  #       - "traefik.http.services.netdata.loadbalancer.server.port=19999"
  #       - "traefik.swarm.network=traefik"
#volumes:
  #netdataconfig: {}
  #netdatalib: {}
  #netdatacache: {}
configs:
  blackbox_config:
    name: blackbox_config-${CONFIG_VERSION:-0}
    file: ./configs/blackbox/blackbox.yml
  telegraf_docker_health_config:
    name: telegraf_docker_health_config-${CONFIG_VERSION:-0}
    file: ./configs/telegraf/docker-health.conf
  postgres_exporter_queries:
    name: postgres_exporter_queries-${CONFIG_VERSION:-0}
    file: ./configs/postgres/postgres_exporter_queries.yaml
secrets:
  postgres_exporter_db_password:
    name: postgres_exporter_db_password-${CONFIG_VERSION:-0}
    file: ../../secrets/postgres_exporter/db_password
