{
 "title": "Docker and system monitoring",
 "description": "A simple overview of the most important Docker host and container metrics. (cAdvisor/Prometheus)",
 "tags": [
  "docker",
  "containers",
  "monitoring",
  "system",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "containergroup",
    "label": "Container Group",
    "query": {
     "query": "label_values(container_last_seen,container_label_com_docker_stack_namespace)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "server",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info, nodename)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "⏱️ Node Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(nodename) ((time() - node_boot_time_seconds{}) * on(instance) group_left(nodename) node_uname_info{nodename=~\"${server:regex}\"})",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "💾 Disk Utilization",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(nodename) ((max by (instance) ((node_filesystem_size_bytes{fstype!=\"tmpfs\",  fstype!=\"vfat\", device!=\"snapfuse\"} - node_filesystem_free_bytes{fstype!=\"tmpfs\",  fstype!=\"vfat\", device!=\"snapfuse\"} )/ node_filesystem_size_bytes{fstype!=\"tmpfs\",  fstype!=\"vfat\", device!=\"snapfuse\"})) * on(instance) group_left(nodename) node_uname_info{nodename=~\"${server:regex}\"})",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "🧮 Swap Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(nodename) (((node_memory_SwapTotal_bytes{} - node_memory_SwapFree_bytes{})) * on(instance) group_left(nodename) node_uname_info{nodename=~\"${server:regex}\"})",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "📦 Container Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count by (nodename) (label_replace(container_last_seen{name=~\".+\"}, \"nodename\", \"$1\", \"instance\", \"([^:]+):.*\"))",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "🧮 Memory Used (%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(nodename) ((((node_memory_MemTotal_bytes{} - node_memory_MemAvailable_bytes{}) / node_memory_MemTotal_bytes{}) * 100) * on(instance) group_left(nodename) node_uname_info{nodename=~\"${server:regex}\"})",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "📈 Load Avg (1m)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max by(nodename) ((node_load1{} / count by(job, instance)(count by(job, instance, cpu)(node_cpu_seconds_total{}))) * on(instance) group_left(nodename) node_uname_info{nodename=~\"${server:regex}\"})",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "🌐 Host Network (All Interfaces)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\"}[$interval])) by (id, instance, interface) !=0",
     "legendFormat": "RECEIVE > {{instance}}::{{interface}}"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{id=\"/\"}[$interval])) by (id, instance, interface) != 0",
     "legendFormat": "SENT < {{instance}}::{{interface}}"
    }
   ]
  },
  {
   "title": "📈 Load Avg (1m) — Per CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(nodename) ((node_load1{} / count by(job, instance)(count by(job, instance, cpu)(node_cpu_seconds_total{}))) * on(instance) group_left(nodename) node_uname_info{nodename=~\"${server:regex}\"})",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "🧮 Memory Available",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(nodename) (sum by(instance) (node_memory_MemAvailable_bytes{}) * on(instance) group_left(nodename) node_uname_info{nodename=~\"${server:regex}\"})",
     "legendFormat": "{{nodename}} Available"
    },
    {
     "expr": "max by(nodename) (sum by(instance) (node_memory_MemTotal_bytes{} - node_memory_MemAvailable_bytes{}) * on(instance) group_left(nodename) node_uname_info{nodename=~\"${server:regex}\"})",
     "legendFormat": "{{nodename}} Unavailable"
    }
   ]
  },
  {
   "title": "🧠 CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by(nodename) ((100 *\nsum by (instance) (\n  rate(node_cpu_seconds_total{\n    job=\"node-exporter\",\n    mode=~\"user|system\"\n  }[$__rate_interval])\n)\n/ on (instance) group_left\ncount by (instance) (count by (cpu, instance) (\n  node_cpu_seconds_total{job=\"node-exporter\"}\n))\n) * on(instance) group_left(nodename) node_uname_info{nodename=~\"${server:regex}\"})",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "💾 Disk Used",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(max by (device, instance) (node_filesystem_size_bytes{fstype!=\"tmpfs\",  fstype!=\"vfat\", device!=\"snapfuse\"} - node_filesystem_free_bytes{fstype!=\"tmpfs\",  fstype!=\"vfat\",  device!=\"snapfuse\"}) * on(instance) group_left(nodename) node_uname_info{nodename=~\"${server:regex}\"})",
     "legendFormat": "Used Disk Space"
    },
    {
     "expr": "sum(max by (device, instance) (node_filesystem_free_bytes{fstype!=\"tmpfs\",  fstype!=\"vfat\",  device!=\"snapfuse\"}) * on(instance) group_left(nodename) node_uname_info{nodename=~\"${server:regex}\"})",
     "legendFormat": "Free Disk Space"
    }
   ]
  },
  {
   "title": "💽 Disk Throughput (I/O)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "-sum(rate(node_disk_read_bytes_total[$interval])) by (device)",
     "legendFormat": "OUT on /{{device}}"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total[$interval])) by (device)",
     "legendFormat": "IN on /{{device}}"
    }
   ]
  },
  {
   "title": "🧠 CPU per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum by(container_label_com_docker_swarm_service_name) (rate(container_cpu_usage_seconds_total{container_label_com_docker_stack_namespace=~\"$containergroup\"}[$interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "🧮 Memory per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(container_label_com_docker_swarm_service_name) (container_memory_rss{name=~\".+\", container_label_com_docker_stack_namespace=~\"$containergroup\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "📤 Container Network (Tx)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(container_label_com_docker_swarm_service_name) (rate(container_network_transmit_bytes_total{container_label_com_docker_stack_namespace=~\"$containergroup\"}[$interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "📥 Container Network (Rx)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(container_label_com_docker_swarm_service_name) (rate(container_network_receive_bytes_total{container_label_com_docker_stack_namespace=~\"$containergroup\"}[$interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "🧮 Swap per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(container_label_com_docker_swarm_service_name) (container_memory_swap{container_label_com_docker_stack_namespace=~\"$containergroup\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "🧮 Memory Used",
   "type": "table",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_stack_namespace=~\"$containergroup\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "🧮 Memory Free",
   "type": "table",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(100 - ((container_spec_memory_limit_bytes{name=~\".+\"} - container_memory_usage_bytes{name=~\".+\"})  * 100 / container_spec_memory_limit_bytes{name=~\".+\"}) ) by (name) ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "🧮 Memory Limit",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_spec_memory_limit_bytes{name=~\".+\"}) by (name) ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "🧠 Non‑Swarm CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum by (name, image) (rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name!~\".+\", id!=\"/\"}[$__rate_interval]))",
     "legendFormat": "{{name}} ({{image}})"
    }
   ]
  },
  {
   "title": "🧮 Non‑Swarm Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name, image) (container_memory_usage_bytes{container_label_com_docker_swarm_service_name!~\".+\", id!=\"/\"})",
     "legendFormat": "{{name}} ({{image}})"
    }
   ]
  },
  {
   "title": "🧮 Non‑Swarm Swap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(name, image) (container_memory_swap{container_label_com_docker_swarm_service_name!~\".+\", id!=\"/\"})",
     "legendFormat": "{{name}} ({{image}})"
    }
   ]
  },
  {
   "title": "📥 Non‑Swarm Network (Rx)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(name, image) (rate(container_network_receive_bytes_total{container_label_com_docker_swarm_service_name!~\".+\", id!=\"/\"}[$__rate_interval]))",
     "legendFormat": "{{name}} ({{image}})"
    }
   ]
  },
  {
   "title": "📤 Non‑Swarm Network (Tx)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(name, image) (rate(container_network_transmit_bytes_total{container_label_com_docker_swarm_service_name!~\".+\", id!=\"/\"}[$__rate_interval]))",
     "legendFormat": "{{name}} ({{image}})"
    }
   ]
  }
 ]
}